#pragma once

#include "Kismet/BlueprintFunctionLibrary.h"
#include "SwuiJsonBlueprintLibrary.generated.h"

/**
 * Generic JSON→UScriptStruct deserializer for SWUI typed navigation events.
 *
 * Called by intermediate nodes generated by UK2Node_SwuiNavigationEvent at
 * compile time. Not intended for direct Blueprint use.
 */
UCLASS()
class SWUIRUNTIME_API USwuiJsonBlueprintLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	/**
	 * Deserialize a JSON string into a UScriptStruct and return it as
	 * an FInstancedStruct.
	 *
	 * @param JsonPayload  The raw JSON string from the navigation event.
	 * @param StructPath   Path to the target UScriptStruct (e.g. "/Script/OneV.HostRoomPayload").
	 * @return             Filled FInstancedStruct on success, empty on failure.
	 */
	UFUNCTION(BlueprintCallable, Category="SWUI|Internal",
		meta=(BlueprintInternalUseOnly="true",
			ToolTip="Deserialize a JSON string into a UScriptStruct. For internal SWUI node use."))
	static FInstancedStruct JsonToStruct(const FString& JsonPayload, const FString& StructPath);

	// ── Per-field JSON extractors (used by K2Node_SwuiCommandHook) ──

	UFUNCTION(BlueprintCallable, Category="SWUI|Internal",
		meta=(BlueprintInternalUseOnly="true"))
	static FString ExtractStringField(const FString& JsonPayload, const FString& FieldName);

	UFUNCTION(BlueprintCallable, Category="SWUI|Internal",
		meta=(BlueprintInternalUseOnly="true"))
	static int32 ExtractIntField(const FString& JsonPayload, const FString& FieldName);

	UFUNCTION(BlueprintCallable, Category="SWUI|Internal",
		meta=(BlueprintInternalUseOnly="true"))
	static float ExtractFloatField(const FString& JsonPayload, const FString& FieldName);

	UFUNCTION(BlueprintCallable, Category="SWUI|Internal",
		meta=(BlueprintInternalUseOnly="true"))
	static bool ExtractBoolField(const FString& JsonPayload, const FString& FieldName);
};
