#include "SwuiTSGenerator.h"
#include "Swui.h"
#include "SwuiBindingSource.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "HAL/PlatformFileManager.h"

static FString SwuiComputeNamespace(UClass* SourceClass)
{
	if (!SourceClass) return TEXT("swui");
	FString Name = SourceClass->GetName();
	if (Name.StartsWith(TEXT("A")) || Name.StartsWith(TEXT("U")))
		Name = Name.RightChop(1);
	return Name.ToLower();
}

bool FSwuiTSGenerator::Generate(USwui* Bridge)
{
	if (!Bridge || Bridge->InterfaceName.IsEmpty()) return false;
	if (Bridge->BindingSources.IsEmpty()) return false;

	// Collect all namespaces (for the header comment) and all state fields
	TArray<FString> Namespaces;
	FString StateFields;

	for (const FSwuiBindingSource& Source : Bridge->BindingSources)
	{
		UClass* SourceClass = Source.SourceClass;
		if (!SourceClass || Source.Properties.IsEmpty()) continue;

		const FString Namespace = SwuiComputeNamespace(SourceClass);
		Namespaces.AddUnique(Namespace);

		for (const FName& PropName : Source.Properties)
		{
			FProperty* Prop = SourceClass->FindPropertyByName(PropName);
			if (!Prop) continue;
			const FString TSType = SwuiGetTSType(Prop);
			if (TSType.IsEmpty()) continue;

			StateFields += FString::Printf(TEXT("\t\"%s.%s\": %s;\n"),
				*Namespace, *PropName.ToString(), *TSType);
		}
	}

	if (StateFields.IsEmpty())
	{
		UE_LOG(LogTemp, Warning, TEXT("SWUI: No supported properties to generate for '%s'. Skipping."), *Bridge->InterfaceName);
		return false;
	}

	const FString InterfaceName  = Bridge->InterfaceName;
	const FString NamespacesList = FString::Join(Namespaces, TEXT(", "));

	FString Output = FString::Printf(TEXT(
		"// %s.generated.ts\n"
		"// AUTO-GENERATED by SimpleWebUI \u2014 do not edit manually.\n"
		"// Re-generate via: Tools > SimpleWebUI > Refresh JS Bindings\n"
		"// Namespaces: %s\n"
		"\n"
		"export interface I%sState {\n"
		"%s"
		"}\n"
		"\n"
		"// Returns the current snapshot of all synced state values.\n"
		"export function swuiGetState(): I%sState {\n"
		"\treturn ((window as any).__SWUI__?.state ?? {}) as I%sState;\n"
		"}\n"
		"\n"
		"// Subscribe to changes on a single namespaced state key.\n"
		"// Key format: \"namespace.PropertyName\" e.g. \"%s.Health\".\n"
		"// callback fires every time the Unreal side pushes a new value.\n"
		"export function swuiOnChange<K extends keyof I%sState>(\n"
		"\tkey: K,\n"
		"\tcallback: (value: I%sState[K]) => void\n"
		"): void {\n"
		"\tconst runtime = ((window as any).__SWUI__ =\n"
		"\t\t(window as any).__SWUI__ ?? { state: {} as I%sState });\n"
		"\tconst prev = runtime._notify as ((k: string, v: unknown) => void) | undefined;\n"
		"\truntime._notify = (k: string, v: unknown) => {\n"
		"\t\tif (k === (key as string)) callback(v as I%sState[K]);\n"
		"\t\tprev?.(k, v);\n"
		"\t};\n"
		"}\n"
	),
		*InterfaceName,
		*NamespacesList,
		*InterfaceName, *StateFields,
		*InterfaceName, *InterfaceName,
		Namespaces.Num() > 0 ? *Namespaces[0] : TEXT("swui"),
		*InterfaceName,
		*InterfaceName,
		*InterfaceName,
		*InterfaceName,
		*InterfaceName
	);

	const FString OutDir  = FPaths::ProjectContentDir() / TEXT("UI/generated");
	const FString OutFile = OutDir / InterfaceName + TEXT(".generated.ts");

	IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
	if (!PlatformFile.DirectoryExists(*OutDir))
	{
		PlatformFile.CreateDirectoryTree(*OutDir);
	}

	if (FFileHelper::SaveStringToFile(Output, *OutFile))
	{
		UE_LOG(LogTemp, Log, TEXT("SWUI: Generated '%s'"), *OutFile);
		return true;
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("SWUI: Failed to write '%s'"), *OutFile);
		return false;
	}
}