#include "SwuiTSGenerator.h"
#include "Swui.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "HAL/PlatformFileManager.h"

static FString SwuiComputeNamespace(UClass* SourceClass)
{
	if (!SourceClass) return TEXT("swui");
	FString Name = SourceClass->GetName();
	if (Name.StartsWith(TEXT("A")) || Name.StartsWith(TEXT("U")))
		Name = Name.RightChop(1);
	return Name.ToLower();
}

void FSwuiTSGenerator::Generate(USwui* Bridge)
{
	if (!Bridge || Bridge->InterfaceName.IsEmpty()) return;

	UClass* SourceClass = Bridge->CodegenSourceClass;
	if (Bridge->ExposedProperties.Num() == 0) return;

	const FString Namespace = SwuiComputeNamespace(SourceClass);

	// Build the state interface fields with namespaced keys
	FString StateFields;
	for (const FName& PropName : Bridge->ExposedProperties)
	{
		FProperty* Prop = SourceClass ? SourceClass->FindPropertyByName(PropName) : nullptr;
		const FString TSType = Prop ? SwuiGetTSType(Prop) : TEXT("unknown");
		if (TSType.IsEmpty()) continue;

		// Key format: "namespace.PropName" — matches what USwuiSubsystem stores
		StateFields += FString::Printf(TEXT("\t\"%s.%s\": %s;\n"), *Namespace, *PropName.ToString(), *TSType);
	}

	if (StateFields.IsEmpty())
	{
		UE_LOG(LogTemp, Warning, TEXT("SWUI: No supported properties to generate for '%s'. Skipping."), *Bridge->InterfaceName);
		return;
	}

	const FString InterfaceName = Bridge->InterfaceName;

	FString Output = FString::Printf(TEXT(
		"// %s.generated.ts\n"
		"// AUTO-GENERATED by SimpleWebUI — do not edit manually.\n"
		"// Re-generate via: Tools > SimpleWebUI > Refresh JS Bindings\n"
		"// Namespace: \"%s\"\n"
		"\n"
		"export interface I%sState {\n"
		"%s"
		"}\n"
		"\n"
		"// Returns the current snapshot of all synced state values.\n"
		"export function swuiGetState(): I%sState {\n"
		"\treturn ((window as any).__SWUI__?.state ?? {}) as I%sState;\n"
		"}\n"
		"\n"
		"// Subscribe to changes on a single namespaced state key.\n"
		"// The key format is \"namespace.PropertyName\" e.g. \"%s.Health\".\n"
		"// callback fires every time the Unreal side pushes a new value.\n"
		"export function swuiOnChange<K extends keyof I%sState>(\n"
		"\tkey: K,\n"
		"\tcallback: (value: I%sState[K]) => void\n"
		"): void {\n"
		"\tconst runtime = ((window as any).__SWUI__ =\n"
		"\t\t(window as any).__SWUI__ ?? { state: {} as I%sState });\n"
		"\tconst prev = runtime._notify as ((k: string, v: unknown) => void) | undefined;\n"
		"\truntime._notify = (k: string, v: unknown) => {\n"
		"\t\tif (k === (key as string)) callback(v as I%sState[K]);\n"
		"\t\tprev?.(k, v);\n"
		"\t};\n"
		"}\n"
	),
		*InterfaceName,
		*Namespace,
		*InterfaceName, *StateFields,
		*InterfaceName, *InterfaceName,
		*Namespace,
		*InterfaceName,
		*InterfaceName,
		*InterfaceName,
		*InterfaceName,
		*InterfaceName
	);

	const FString OutDir  = FPaths::ProjectContentDir() / TEXT("UI/generated");
	const FString OutFile = OutDir / InterfaceName + TEXT(".generated.ts");

	IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
	if (!PlatformFile.DirectoryExists(*OutDir))
	{
		PlatformFile.CreateDirectoryTree(*OutDir);
	}

	if (FFileHelper::SaveStringToFile(Output, *OutFile))
	{
		UE_LOG(LogTemp, Log, TEXT("SWUI: Generated '%s'"), *OutFile);
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("SWUI: Failed to write '%s'"), *OutFile);
	}
}
