#include "SwuiTSGenerator.h"
#include "Swui.h"
#include "SwuiBindingSource.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "HAL/PlatformFileManager.h"

static FString SwuiComputeNamespace(UClass* SourceClass)
{
	if (!SourceClass) return TEXT("swui");
	FString Name = SourceClass->GetName();
	if (Name.StartsWith(TEXT("A")) || Name.StartsWith(TEXT("U")))
		Name = Name.RightChop(1);
	return Name.ToLower();
}

static FString NullableNum(const FString& S)
{
	return S.IsEmpty() ? TEXT("null") : S;
}

bool FSwuiTSGenerator::Generate(USwui* Bridge)
{
	if (!Bridge || Bridge->InterfaceName.IsEmpty()) return false;
	if (Bridge->BindingSources.IsEmpty()) return false;

	struct FPropInfo
	{
		FString Namespace;
		FString FullKey;   // "namespace.PropName"
		FString PropName;  // "Health"
		FString TSType;    // "number"
		FString Label;     // DisplayName meta or PropName
		FString Category;  // Category meta
		FString MinVal;    // empty or numeric string
		FString MaxVal;    // empty or numeric string
	};

	struct FEventInfo
	{
		FString Namespace;
		FString FullKey;      // "namespace.OnFired"
		FString DelegateName; // "OnFired"
	};

	TArray<FPropInfo>  Props;
	TArray<FEventInfo> Events;
	TArray<FString>    Namespaces;

	for (const FSwuiBindingSource& Source : Bridge->BindingSources)
	{
		UClass* SourceClass = Source.SourceClass;
		if (!SourceClass || Source.Properties.IsEmpty()) continue;

		const FString Namespace = SwuiComputeNamespace(SourceClass);
		Namespaces.AddUnique(Namespace);

		for (const FName& PropFName : Source.Properties)
		{
			FProperty* Prop = SourceClass->FindPropertyByName(PropFName);
			if (!Prop) continue;

			const FString TSType = SwuiGetTSType(Prop);
			if (TSType.IsEmpty()) continue;

			auto GetMeta = [&](const TCHAR* Key) -> FString
			{
				return Prop->HasMetaData(Key) ? Prop->GetMetaData(Key) : FString();
			};

			FPropInfo Info;
			Info.Namespace = Namespace;
			Info.PropName  = PropFName.ToString();
			Info.FullKey   = Namespace + TEXT(".") + Info.PropName;
			Info.TSType    = TSType;
			Info.Label     = GetMeta(TEXT("DisplayName"));
			if (Info.Label.IsEmpty()) Info.Label = Info.PropName;
			Info.Category  = GetMeta(TEXT("Category"));
			Info.MinVal    = GetMeta(TEXT("ClampMin"));
			if (Info.MinVal.IsEmpty()) Info.MinVal = GetMeta(TEXT("UIMin"));
			Info.MaxVal    = GetMeta(TEXT("ClampMax"));
			if (Info.MaxVal.IsEmpty()) Info.MaxVal = GetMeta(TEXT("UIMax"));

			Props.Add(MoveTemp(Info));
		}

		for (const FName& DelegateFName : Source.Delegates)
		{
			FEventInfo EInfo;
			EInfo.Namespace     = Namespace;
			EInfo.DelegateName  = DelegateFName.ToString();
			EInfo.FullKey       = Namespace + TEXT(".") + EInfo.DelegateName;
			Events.Add(MoveTemp(EInfo));
		}
	}

	if (Props.IsEmpty() && Events.IsEmpty())
	{
		UE_LOG(LogTemp, Warning, TEXT("SWUI: No supported properties or events to generate for '%s'. Skipping."), *Bridge->InterfaceName);
		return false;
	}

	const FString IName   = Bridge->InterfaceName;
	const FString NsList  = FString::Join(Namespaces, TEXT(", "));

	// ── KEYS ─────────────────────────────────────────────────────────────────
	FString KeysBody;
	for (const FPropInfo& P : Props)
		KeysBody += FString::Printf(TEXT("\t%s: '%s',\n"), *P.PropName, *P.FullKey);

	// ── State interface ───────────────────────────────────────────────────────
	FString InterfaceBody;
	for (const FPropInfo& P : Props)
		InterfaceBody += FString::Printf(TEXT("\t'%s': %s;\n"), *P.FullKey, *P.TSType);

	// ── META ──────────────────────────────────────────────────────────────────
	FString MetaBody;
	for (const FPropInfo& P : Props)
	{
		MetaBody += FString::Printf(
			TEXT("\t'%s': { label: '%s', category: '%s', min: %s, max: %s },\n"),
			*P.FullKey, *P.Label, *P.Category,
			*NullableNum(P.MinVal), *NullableNum(P.MaxVal));
	}

	// ── Typed helpers ─────────────────────────────────────────────────────────
	FString HelpersBody;
	for (const FPropInfo& P : Props)
	{
		HelpersBody += FString::Printf(
			TEXT("export function on%s(fn: (v: %s) => void): () => void { return Swui.on(KEYS.%s, fn); }\n"),
			*P.PropName, *P.TSType, *P.PropName);
	}

	// ── Event helpers ─────────────────────────────────────────────────────────
	FString EventHelpersBody;
	for (const FEventInfo& E : Events)
	{
		// Emit a typed addEventListener wrapper that returns an unsubscribe fn.
		EventHelpersBody += FString::Printf(
			TEXT("export function on%s(fn: () => void): () => void {\n")
			TEXT("  document.addEventListener('%s', fn);\n")
			TEXT("  return () => document.removeEventListener('%s', fn);\n")
			TEXT("}\n"),
			*E.DelegateName, *E.FullKey, *E.FullKey);
	}

	FString Output = FString::Printf(TEXT(
		"// %s.generated.ts\n"
		"// AUTO-GENERATED by SimpleWebUI \u2014 do not edit manually.\n"
		"// Re-generate via: Tools > SimpleWebUI > Refresh JS Bindings\n"
		"// Namespaces: %s\n"
		"\n"
		"// \u2500\u2500 Key Constants \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
		"export const KEYS = {\n"
		"%s"
		"} as const;\n"
		"\n"
		"// \u2500\u2500 State Interface \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
		"export interface I%sState {\n"
		"%s"
		"}\n"
		"\n"
		"// \u2500\u2500 Metadata \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
		"export interface ISwuiMeta {\n"
		"\tlabel:    string;\n"
		"\tcategory: string;\n"
		"\tmin:      number | null;\n"
		"\tmax:      number | null;\n"
		"}\n"
		"\n"
		"export const META: Record<string, ISwuiMeta> = {\n"
		"%s"
		"};\n"
		"\n"
		"// \u2500\u2500 Typed Helpers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
		"import Swui from '@simplewebui/client';\n"
		"%s"
		"\n"
		"// \u2500\u2500 Event Helpers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
		"%s"
	),
		*IName,
		*NsList,
		*KeysBody,
		*IName, *InterfaceBody,
		*MetaBody,
		*HelpersBody,
		*EventHelpersBody
	);

	const FString OutDir  = FPaths::ProjectContentDir() / TEXT("UI/generated");
	const FString OutFile = OutDir / IName + TEXT(".generated.ts");

	IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
	if (!PlatformFile.DirectoryExists(*OutDir))
		PlatformFile.CreateDirectoryTree(*OutDir);

	if (FFileHelper::SaveStringToFile(Output, *OutFile, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
	{
		UE_LOG(LogTemp, Log, TEXT("SWUI: Generated '%s'"), *OutFile);
		return true;
	}

	UE_LOG(LogTemp, Error, TEXT("SWUI: Failed to write '%s'"), *OutFile);
	return false;
}